trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: FirstJob
        steps:
          - bash: echo "Build First Job"

  - stage: DevDeploy
    dependsOn: Build
    jobs:
      - job: DevDeployJob
        steps:
          - bash: echo "Dev Deploy"

  - stage: QADeploy
    dependsOn: Build
    jobs:
      - job: QADeployJob
        steps:
          - bash: echo "QA Deploy Job"

      - job: QA2
        steps:
          - bash: echo "QA2"

  - stage: ProdDeploy
    dependsOn:
      - DevDeploy
      - QADeploy
    jobs:
      - job: ProdDeployJob
        steps:
          - bash: echo "Prod Deploy Job"

      - job: Prod2
        steps:
          - bash: echo "Prod2"

  - stage: Submit
    dependsOn:
      - DevDeploy
      - QADeploy
      - ProdDeploy
    jobs:
      - job: SubmitJob
        steps:
          - bash: echo "Submit the Job"